--TB_USUARIOS
INSERT INTO TB_USUARIOS (ID,NOME,USERNAME,PASSWORD) VALUES (SEQ_USUARIO.NEXTVAL,'Luciene Alves','luciene','123456');
INSERT INTO TB_USUARIOS (ID,NOME,USERNAME,PASSWORD) VALUES (SEQ_USUARIO.NEXTVAL,'Assis Lima','assis','123456');
INSERT INTO TB_USUARIOS (ID,NOME,USERNAME,PASSWORD) VALUES (SEQ_USUARIO.NEXTVAL,'Carlos Roberto','roberto','123456');
INSERT INTO TB_USUARIOS (ID,NOME,USERNAME,PASSWORD) VALUES (SEQ_USUARIO.NEXTVAL,'Super Boss','Boss','123456');

--TB_ROLES
INSERT INTO TB_ROLES (ID,NOME) VALUES (SEQ_ROLE.NEXTVAL,'Admin');
INSERT INTO TB_ROLES (ID,NOME) VALUES (SEQ_ROLE.NEXTVAL,'Supervisor');
INSERT INTO TB_ROLES (ID,NOME) VALUES (SEQ_ROLE.NEXTVAL,'Auxiliar');

--TB_ROLES POR TB_USUARIOS
INSERT INTO TB_ROLES_TB_USUARIOS(ROLES_ID,USUARIOS_ID) VALUES (1,1);
INSERT INTO TB_ROLES_TB_USUARIOS(ROLES_ID,USUARIOS_ID) VALUES (2,2);
INSERT INTO TB_ROLES_TB_USUARIOS(ROLES_ID,USUARIOS_ID) VALUES (3,3);
INSERT INTO TB_ROLES_TB_USUARIOS(ROLES_ID,USUARIOS_ID) VALUES (3,4);
