--TB_USUARIOS
INSERT INTO TB_USUARIOS (ID,NOME,USERNAME,PASSWORD) VALUES (SEQ_USUARIO.NEXTVAL,'Luciene Alves','luciene','123456');
INSERT INTO TB_USUARIOS (ID,NOME,USERNAME,PASSWORD) VALUES (SEQ_USUARIO.NEXTVAL,'Assis Lima','assis','123456');
INSERT INTO TB_USUARIOS (ID,NOME,USERNAME,PASSWORD) VALUES (SEQ_USUARIO.NEXTVAL,'Carlos Roberto','roberto','123456');
INSERT INTO TB_USUARIOS (ID,NOME,USERNAME,PASSWORD) VALUES (SEQ_USUARIO.NEXTVAL,'Super Boss','boss','123456');

--TB_ROLES
INSERT INTO TB_ROLES (ID,NOME) VALUES (SEQ_ROLE.NEXTVAL,'Admin');
INSERT INTO TB_ROLES (ID,NOME) VALUES (SEQ_ROLE.NEXTVAL,'Supervisor');
INSERT INTO TB_ROLES (ID,NOME) VALUES (SEQ_ROLE.NEXTVAL,'Auxiliar');

--TB_ROLES POR TB_USUARIOS
INSERT INTO TB_ROLES_TB_USUARIOS(ROLES_ID,USUARIOS_ID) VALUES (1,1);
INSERT INTO TB_ROLES_TB_USUARIOS(ROLES_ID,USUARIOS_ID) VALUES (2,2);
INSERT INTO TB_ROLES_TB_USUARIOS(ROLES_ID,USUARIOS_ID) VALUES (3,3);
INSERT INTO TB_ROLES_TB_USUARIOS(ROLES_ID,USUARIOS_ID) VALUES (3,4);

--TB_MARCAS
INSERT INTO TB_MARCAS (ID, NOME,DESCRICAO) VALUES (SEQ_MARCA.NEXTVAL, 'Apple', 'Empresa Apple');
INSERT INTO TB_MARCAS (ID, NOME,DESCRICAO) VALUES (SEQ_MARCA.NEXTVAL, 'Google', 'Empresa Google');
INSERT INTO TB_MARCAS (ID, NOME,DESCRICAO) VALUES (SEQ_MARCA.NEXTVAL, 'Microsoft', 'Empresa Microsoft');
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Sonair', 'Carrissa Moule', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Otcom', 'Abe Marioneau', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Treeflex', 'Nowell Barhem ', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Stringtough', 'Ranee Jaine', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Duoban', 'Isadore Mussotti', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Keylex', 'Giulia Hamor', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Alphazap', 'Hilde Helis', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Latlux', 'Dianemarie Burkwood', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Stronghold', 'Vida Pettite', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Y-find', 'Reiko Menichelli', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Wrapsafe', 'Neal Spellesy', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Zathin', 'Ofella Arman', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Stringtough', 'Paulie Muino', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Andalax', 'Norma Boult', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Z-find', 'Joya Housaman', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Biodex', 'Theresa Nehls', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('AlphaZap', 'Liva Eake', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Y-Solowarm', 'Brigitte Chastagnier', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Alpha', 'Leann Fergysson', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Home Ing', 'Wernher Cavolini', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Bamity', 'Frederich Chidley', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Fintone', 'Mortier Welden', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Fix San', 'Mariellen Pitchford', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Konklab', 'Arte Milnes', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Job', 'Issy Jirzik', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Duoban', 'Abigale Bridgestock', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Mat Lat Tan', 'Axel Mirozzo', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Asoka', 'Della Wakeley', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Zontrax', 'Alphonse Coneybeer', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Cookley', 'Collen Groub', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Alpha', 'Merrill Shemmin', SEQ_MARCA.NEXTVAL);

--TB_PRODUTOS
INSERT INTO TB_PRODUTOS (ID, NOME, DESCRICAO, ID_MARCA_FK) VALUES (SEQ_PRODUTO.NEXTVAL, 'IPhone 9','Aparelho Celular',1);
INSERT INTO TB_PRODUTOS (ID, NOME, DESCRICAO, ID_MARCA_FK) VALUES (SEQ_PRODUTO.NEXTVAL, 'IPhone 10','Aparelho Celular',1);
INSERT INTO TB_PRODUTOS (ID, NOME, DESCRICAO, ID_MARCA_FK) VALUES (SEQ_PRODUTO.NEXTVAL, 'Microsoft 365','Word, Excel, Power Point, Access',3);
INSERT INTO TB_PRODUTOS (ID, NOME, DESCRICAO, ID_MARCA_FK) VALUES (SEQ_PRODUTO.NEXTVAL, 'One Drive','Repositório na Nuvem',3);
INSERT INTO TB_PRODUTOS (ID, NOME, DESCRICAO, ID_MARCA_FK) VALUES (SEQ_PRODUTO.NEXTVAL, 'Google Drive','Repositório na Nuvem',2);
INSERT INTO TB_PRODUTOS (ID, NOME, DESCRICAO, ID_MARCA_FK) VALUES (SEQ_PRODUTO.NEXTVAL, 'Google HangOut','Dispositivo de Conversa Online',2);


