--TB_USUARIOS
INSERT INTO TB_USUARIOS (ID,NOME,USERNAME,PASSWORD) VALUES (SEQ_USUARIO.NEXTVAL,'Luciene Alves','luciene','123456');
INSERT INTO TB_USUARIOS (ID,NOME,USERNAME,PASSWORD) VALUES (SEQ_USUARIO.NEXTVAL,'Assis Lima','assis','123456');
INSERT INTO TB_USUARIOS (ID,NOME,USERNAME,PASSWORD) VALUES (SEQ_USUARIO.NEXTVAL,'Carlos Roberto','roberto','123456');
INSERT INTO TB_USUARIOS (ID,NOME,USERNAME,PASSWORD) VALUES (SEQ_USUARIO.NEXTVAL,'Super Boss','boss','123456');

--TB_ROLES
INSERT INTO TB_ROLES (ID,NOME) VALUES (SEQ_ROLE.NEXTVAL,'Admin');
INSERT INTO TB_ROLES (ID,NOME) VALUES (SEQ_ROLE.NEXTVAL,'Supervisor');
INSERT INTO TB_ROLES (ID,NOME) VALUES (SEQ_ROLE.NEXTVAL,'Auxiliar');

--TB_ROLES POR TB_USUARIOS
INSERT INTO TB_ROLES_TB_USUARIOS(ROLES_ID,USUARIOS_ID) VALUES (1,1);
INSERT INTO TB_ROLES_TB_USUARIOS(ROLES_ID,USUARIOS_ID) VALUES (2,2);
INSERT INTO TB_ROLES_TB_USUARIOS(ROLES_ID,USUARIOS_ID) VALUES (3,3);
INSERT INTO TB_ROLES_TB_USUARIOS(ROLES_ID,USUARIOS_ID) VALUES (3,4);

--TB_MARCAS
INSERT INTO TB_MARCAS (ID, NOME,DESCRICAO) VALUES (SEQ_MARCA.NEXTVAL, 'Apple', 'Empresa Apple');
INSERT INTO TB_MARCAS (ID, NOME,DESCRICAO) VALUES (SEQ_MARCA.NEXTVAL, 'Google', 'Empresa Google');
INSERT INTO TB_MARCAS (ID, NOME,DESCRICAO) VALUES (SEQ_MARCA.NEXTVAL, 'Microsoft', 'Empresa Microsoft');
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('SONAIR', 'CARRISSA MOULE', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('OTCOM', 'ABE MARIONEAU', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('TREEFLEX', 'NOWELL BARHEM', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('STRINGTOUGH', 'RANEE JAINE', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('DUOBAM', 'ISADORE MUSSOTTI', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('KEYLEX', 'GIULIA HAMOR', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('ALPHAZAP', 'HILDE HELIS', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('LATLUX', 'DIANEMARIE BURKWOOD', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('STRONGHOLD', 'VIDA PETTIE', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Y-FIND', 'REIKO MENICHELLI', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('WRAPSAFE', 'NEAL SPELLESY', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('ZATHIN', 'OFELLA ARMAN', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('STRINGTOUGH', 'PAULIE MUINO', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('ANDALAX', 'NORMA BOULT', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Y-FIND', 'JOYA HOUSAMAN', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('BIODEX', 'THERESA NEHLS', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('ALPHAZAP', 'LIVA EAKE', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('Y-SOLOWARM', 'BRIGITTE CHASTAGNIER', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('ALPHA', 'LEANN FERGYSON', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('HOME ING', 'WERNHER CAVOLINI', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('BAMITY', 'FREDERICH CHIDLEY', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('FINTONE', 'MORTIE WELDEN', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('FIX SAN', 'MARIELLEN PITCHFORD', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('KONKLAB', 'ARTE MILNES', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('JOB', 'ISSY JIRZIK', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('DUOBAM', 'ABIGALE BRIDGESTOCK', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('MAT LAM TAM', 'AXEL RIZZOLO', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('ASOKA', 'DELLA WAKELEY', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('ZONTRAX', 'ALPHONSE CONEYBEER', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('COOKLEY', 'COLLEEN GRUBBE', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('ALPHA', 'MERRILL SHEMMIN', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('STRONGHOLD', 'KENNY RAMSTEAD', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('DALTFRESH', 'ANA LEGUEY', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('VOYATOUCH', 'GIRALDA ALBRO', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('KONKLUX', 'FITZ EDGELEY', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('OVERHOLD', 'HERTA POPPLEWELL', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('SONSING', 'MALYNDA CHASTNEY', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('TRES-ZAP', 'GAYLE TRAITE', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('FLOWDESK', 'STAFFARD LEIPOLDT', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('ZONTRAX', 'SHEFFY BRIDGMAN', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('SUBIN', 'CARLO BURDER', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('ZATHIN', 'VACLAV LINBOHM', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('GREENLAM', 'RENIE SHILITON', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('GREENLAM', 'LIDIA ARNE', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('BITCHIP', 'FRANCISKUS FEHNERS', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('LOTSTRING', 'ALAIN LANGWORTHY', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('DOMAINER', 'COLEMAN BASTARD', SEQ_MARCA.NEXTVAL);
INSERT INTO TB_MARCAS (NOME, DESCRICAO, ID) VALUES ('TRIPPLEDEX', 'LEANNA O''FARRELL', SEQ_MARCA.NEXTVAL);

--TB_PRODUTOS
INSERT INTO TB_PRODUTOS (ID, NOME, DESCRICAO, ID_MARCA_FK) VALUES (SEQ_PRODUTO.NEXTVAL, 'IPhone 9','Aparelho Celular',1);
INSERT INTO TB_PRODUTOS (ID, NOME, DESCRICAO, ID_MARCA_FK) VALUES (SEQ_PRODUTO.NEXTVAL, 'IPhone 10','Aparelho Celular',1);
INSERT INTO TB_PRODUTOS (ID, NOME, DESCRICAO, ID_MARCA_FK) VALUES (SEQ_PRODUTO.NEXTVAL, 'Microsoft 365','Word, Excel, Power Point, Access',3);
INSERT INTO TB_PRODUTOS (ID, NOME, DESCRICAO, ID_MARCA_FK) VALUES (SEQ_PRODUTO.NEXTVAL, 'One Drive','Repositório na Nuvem',3);
INSERT INTO TB_PRODUTOS (ID, NOME, DESCRICAO, ID_MARCA_FK) VALUES (SEQ_PRODUTO.NEXTVAL, 'Google Drive','Repositório na Nuvem',2);
INSERT INTO TB_PRODUTOS (ID, NOME, DESCRICAO, ID_MARCA_FK) VALUES (SEQ_PRODUTO.NEXTVAL, 'Google HangOut','Dispositivo de Conversa Online',2);


